blog/Blog/config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  resources :posts do
  	resources :comments
  end
  devise_for :users  
  #resources :users
  root to: "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/Blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/Blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post
end

blog/Blog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

blog/Blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

blog/Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

blog/Blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  
  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  
  def edit
    @comment = @post.comments.find(params[:id])
  end 

  def update
    @comment = @post.comments.update(comment_params)
    redirect_to post_path(@post)
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end
    def comment_params
      params.require(:comment).permit(:commenter, :body, :user_id)
    end
end

blog/Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      @post.user_id = current_user.id
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

blog/Blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

blog/Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/Blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/Blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/Blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/Blog/app/views/comments/_comment.html.erb
<p>
  <strong>Name:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<% if user_signed_in? %>
  <% if @post.user_id==current_user.id or comment.user_id==current_user.id %>
    <p>
      <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
      <%= link_to 'Delete', [comment.post, comment],
                   method: :delete,
                   data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
<% end %>

blog/Blog/app/views/comments/_form.html.erb
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>

  <% if !user_signed_in? %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
  <% else %>
    <%= form.hidden_field 'commenter', value: current_user.name %>
    <%= form.hidden_field 'user_id', value: current_user.id %>
  <% end %>
    <%= form.label :comment %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

blog/Blog/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>
<%= @post.title %>
<% if user_signed_in? %>
  <%= form_with(model: [ @post, @post.comments.build ], url: post_comment_path, :method => :patch, local: true) do |form| %>
    </p>
      <%= form.label :comment %><br>
      <%= form.text_area :body, :value => @comment.body %>
    </p>
    <p>
    <%= form.submit "Confirm edit"%>
    </p>
  <% end %>
<% else %>
  <%=  "YOU ARE NOT A USER"%>
<% end %>
</br><%= link_to 'Back', @post %>

blog/Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg" style="background-color: #748">
  <a style="color: black; font-size: 24px" class="navbar-brand" href="#">AreejBlog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="head" style="margin-left:1000px;">
    <nav>
      <ul class="nav nav-tabs">
        <% if user_signed_in? %>
        <li><%=link_to  "Hello  #{current_user.name}"%></li>
        <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to('Login', new_user_session_path) %></li>
          <li><%= link_to('Sign Up', new_user_registration_path) %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</nav>
    <div class="container">
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'javascript', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'javascript_2', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

blog/Blog/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group text-center">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="form-group text-center">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>


  <div class="actions text-center ">
    <%= form.submit %>
  </div>
<% end %>

blog/Blog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<% if user_signed_in? %>
  <%= render 'form', post: @post %>
  <%= link_to 'Show', @post %> |
<% else %>
  <%=  "YOU ARE NOT A USER"%></br>
<% end %>
<%= link_to 'Back', posts_path %>

blog/Blog/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td style="text-decoration: none;
  color: #0085A1;"><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to 'Show', post %></td>
        <% if user_signed_in? %>
          <% if post.user_id==current_user.id %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
 <%= link_to 'Add New Post', new_post_path, :class => "btn btn-lg btn-danger" %>
<% end %>

blog/Blog/app/views/posts/new.html.erb
<h1>New Post</h1>
<% if user_signed_in? %>
  <%= render 'form', post: @post %>
<% else %>
  <%=  "YOU ARE NOT A USER"%>
<% end %>
<%= link_to 'Back', posts_path %>

blog/Blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>
<% if user_signed_in? %>
  <% if @post.user_id==current_user.id %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
<% end %>
<%= link_to 'Back', posts_path %>

blog/Blog/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

blog/Blog/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

blog/Blog/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

blog/Blog/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

blog/Blog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>